# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RavelinEncryptDemoPodsObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RavelinEncryptDemoPodsObjC
  pod 'RavelinEncrypt', '1.1.2', :source => 'https://github.com/unravelin/Specs.git'

end
